from __future__ import annotations

from research.perf_contract import (
    build_duplicate_work_report,
    list_recent_perf_artifacts,
    summarize_perf_artifacts,
)

from .config import settings
from .perf_support import (
    _build_designer_perf_bundle,
    _compute_eval_composite_score,
    _discovery_url_for_fingerprint,
    designer_metrics_from_stages,
)
from .eval_run_store import _get_run, _list_runs, _store_run, _update_run
from .research_sync import _auto_promote_workflow_to_research, _sync_lineage_to_research
from .runtime_features import (
    BUILTIN_BLOCKS,
    HAS_BRIDGE,
    HAS_CONSTRAINTS,
    HAS_IMPORTER,
    HAS_PROFILER,
    HAS_SUBGRAPH,
    KernelDispatcher,
    _ARIA_CORE_ROOT,
    _ARIA_DESIGNER_ROOT,
    _PROJECT_ROOT,
    _RESEARCH_ROOT,
    _optional_import,
    bridge_analyze_compression,
    bridge_analyze_routing,
    bridge_component_capability,
    bridge_estimate,
    bridge_evaluate,
    bridge_list_primitives,
    bridge_profile,
    bridge_validate,
    check_compatibility,
    compute_palette_constraints,
    expand_block,
    export_onnx,
    extract_block,
    find_unsupported_edge_dtype_pairings,
    graph_to_workflow,
    import_single,
    import_survivors,
    list_builtin_blocks,
    runtime_compile,
)
from .workflow_support import (
    _collect_workflow_semantic_warnings,
    _require_component,
    _require_proposal,
    _require_run,
    _require_workflow,
    collect_unresolved_nodes,
    get_approved_registry_ids,
    require_feature,
)


__all__ = [
    "_PROJECT_ROOT",
    "_ARIA_DESIGNER_ROOT",
    "_ARIA_CORE_ROOT",
    "_RESEARCH_ROOT",
    "_optional_import",
    "KernelDispatcher",
    "runtime_compile",
    "find_unsupported_edge_dtype_pairings",
    "export_onnx",
    "bridge_evaluate",
    "bridge_validate",
    "bridge_estimate",
    "bridge_list_primitives",
    "bridge_analyze_compression",
    "bridge_analyze_routing",
    "bridge_component_capability",
    "bridge_profile",
    "import_survivors",
    "import_single",
    "graph_to_workflow",
    "check_compatibility",
    "compute_palette_constraints",
    "extract_block",
    "expand_block",
    "list_builtin_blocks",
    "BUILTIN_BLOCKS",
    "HAS_BRIDGE",
    "HAS_PROFILER",
    "HAS_IMPORTER",
    "HAS_CONSTRAINTS",
    "HAS_SUBGRAPH",
    "_get_run",
    "_list_runs",
    "_store_run",
    "_update_run",
    "designer_metrics_from_stages",
    "_build_designer_perf_bundle",
    "_discovery_url_for_fingerprint",
    "_compute_eval_composite_score",
    "_require_component",
    "_require_proposal",
    "_require_workflow",
    "_require_run",
    "get_approved_registry_ids",
    "collect_unresolved_nodes",
    "require_feature",
    "_sync_lineage_to_research",
    "_auto_promote_workflow_to_research",
    "_collect_workflow_semantic_warnings",
    "settings",
    "build_duplicate_work_report",
    "list_recent_perf_artifacts",
    "summarize_perf_artifacts",
]
