"""
Morphological Box for Architecture Exploration

Defines the dimensions of variation for novel transformer architectures.
Each dimension has discrete options. A "roll" picks one option per dimension
to create a complete architecture specification.

Based on Zwicky's morphological analysis + TRIZ inventive principles.
"""

from __future__ import annotations

import hashlib
import json
import random
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional, Tuple


# ── Dimension Definitions ──────────────────────────────────────────────

@dataclass(frozen=True)
class Option:
    """A single option within a dimension."""
    name: str
    description: str
    # Tags for constraint checking (e.g., "linear_complexity", "needs_sorting")
    tags: Tuple[str, ...] = ()
    # Incompatible tags from OTHER dimensions
    incompatible_with: Tuple[str, ...] = ()


@dataclass(frozen=True)
class Dimension:
    """A single axis of variation in the morphological box."""
    name: str
    description: str
    options: Tuple[Option, ...]

    def random_option(self, rng: random.Random) -> Option:
        return rng.choice(self.options)


# ── The Morphological Box ──────────────────────────────────────────────

DIMENSIONS: Tuple[Dimension, ...] = (

    # 1. TOKEN REPRESENTATION — how tokens are represented internally
    Dimension(
        name="token_representation",
        description="How tokens are represented in the hidden space",
        options=(
            Option("dense_float", "Standard dense float vectors (baseline)",
                   tags=("standard",)),
            Option("binary_hash", "Binary hash codes with straight-through estimator",
                   tags=("binary", "low_memory")),
            Option("sparse_topk", "Sparse top-k activation vectors",
                   tags=("sparse",)),
            Option("complex_valued", "Complex-valued representations (real + imaginary)",
                   tags=("complex",)),
            Option("quaternion", "Quaternion representations (4D hypercomplex)",
                   tags=("complex", "quaternion")),
            Option("multi_resolution", "Multiple resolutions concatenated (fine + coarse)",
                   tags=("multi_scale",)),
            Option("mixture_embedding", "Mixture of learned embedding prototypes",
                   tags=("mixture",)),
            Option("residual_quantized", "Residual vector quantization (RVQ) codes",
                   tags=("quantized", "low_memory")),
        ),
    ),

    # 2. WEIGHT STORAGE — how model weights are parameterized
    Dimension(
        name="weight_storage",
        description="How model weights are stored and accessed",
        options=(
            Option("dense_matrix", "Standard dense weight matrices (baseline)",
                   tags=("standard",)),
            Option("low_rank", "Low-rank factorized (UV decomposition)",
                   tags=("low_rank", "low_memory")),
            Option("hypernetwork", "Weights generated by a small hypernetwork",
                   tags=("hypernetwork", "dynamic_weights")),
            Option("shared_basis", "Shared basis vectors with per-layer coefficients",
                   tags=("shared_weights", "low_memory")),
            Option("hash_trick", "Random hash-based weight sharing",
                   tags=("hash", "low_memory")),
            Option("kronecker", "Kronecker-factored weight matrices",
                   tags=("kronecker", "low_memory")),
            Option("polynomial", "Polynomial weight parameterization (degree-N)",
                   tags=("polynomial",)),
            Option("structured_sparse", "N:M structured sparsity",
                   tags=("sparse_weights",)),
        ),
    ),

    # 3. TOKEN MIXING — how tokens communicate with each other
    Dimension(
        name="token_mixing",
        description="The mechanism for inter-token communication",
        options=(
            Option("softmax_attention", "Standard softmax QKV attention (baseline)",
                   tags=("quadratic", "standard")),
            Option("linear_attention", "Linear attention (kernel trick, no softmax)",
                   tags=("linear_complexity",)),
            Option("conv_only", "Pure convolution stack (local + dilated)",
                   tags=("linear_complexity", "local_only")),
            Option("state_space", "State space model (S4/Mamba style)",
                   tags=("linear_complexity", "recurrent")),
            Option("fourier_mixing", "FFT-based global mixing in frequency domain",
                   tags=("linear_complexity", "frequency")),
            Option("graph_attention", "Dynamic graph attention (learned adjacency)",
                   tags=("graph", "quadratic")),
            Option("random_feature_attention", "Random feature approximation of attention",
                   tags=("linear_complexity", "approximate")),
            Option("differentiable_sort", "Sort-based mixing (differentiable sorting networks)",
                   tags=("needs_sorting", "novel")),
            Option("compressed_attention", "Compress tokens before attention (like CCGQA)",
                   tags=("subquadratic",)),
            Option("cross_attention_pool", "Cross-attend to a small set of learned queries",
                   tags=("subquadratic", "bottleneck")),
        ),
    ),

    # 4. CHANNEL MIXING — how features are transformed within each token
    Dimension(
        name="channel_mixing",
        description="The feed-forward / channel transformation",
        options=(
            Option("swiglu_mlp", "SwiGLU MLP (baseline)",
                   tags=("standard",)),
            Option("moe_topk", "Mixture of Experts with top-k routing",
                   tags=("moe", "sparse_compute")),
            Option("kan_spline", "KAN-style learnable spline activations",
                   tags=("kan", "novel")),
            Option("rwkv_channel", "RWKV-style channel mixing (shift + multiply)",
                   tags=("linear_complexity", "recurrent")),
            Option("conv1d_glu", "1D convolution with GLU gating",
                   tags=("conv",)),
            Option("polynomial_expansion", "Polynomial feature expansion + projection",
                   tags=("polynomial",)),
            Option("product_key_memory", "Product-key memory lookup (large sparse)",
                   tags=("memory", "sparse_compute")),
            Option("identity_skip", "No channel mixing (identity / skip connection only)",
                   tags=("minimal",)),
        ),
    ),

    # 5. COMPUTE ROUTING — how computation is allocated across tokens/layers
    Dimension(
        name="compute_routing",
        description="How compute budget is distributed",
        options=(
            Option("uniform", "All tokens get all layers (baseline)",
                   tags=("standard",)),
            Option("mod_topk", "Mixture of Depths: top-k tokens per layer",
                   tags=("dynamic_routing", "token_sparse")),
            Option("early_exit", "Early exit: tokens stop at different depths",
                   tags=("dynamic_routing", "early_exit")),
            Option("adaptive_recursion", "Adaptive recursion depth per token (MoR-style)",
                   tags=("dynamic_routing", "recursion")),
            Option("layerdrop", "Random layer dropping during training",
                   tags=("stochastic",)),
            Option("token_merging", "Merge similar tokens to reduce sequence length",
                   tags=("token_sparse", "merging")),
            Option("cascade", "Progressive cascade: easy tokens get shallow, hard get deep",
                   tags=("dynamic_routing", "cascade")),
            Option("speculative", "Speculative: run cheap path, verify with expensive path",
                   tags=("dynamic_routing", "speculative")),
        ),
    ),

    # 6. ARCHITECTURE TOPOLOGY — the overall wiring pattern
    Dimension(
        name="topology",
        description="How layers/blocks are wired together",
        options=(
            Option("sequential", "Standard sequential stack (baseline)",
                   tags=("standard",)),
            Option("u_net", "U-Net: encoder-decoder with skip connections",
                   tags=("skip_connections", "multi_scale")),
            Option("fractal", "Fractal: recursive self-similar sub-networks",
                   tags=("recursive",)),
            Option("dense_net", "DenseNet: each layer connects to all previous",
                   tags=("dense_connections",)),
            Option("parallel_streams", "Parallel streams merged at intervals",
                   tags=("parallel",)),
            Option("hourglass", "Hourglass: progressive down/upsample",
                   tags=("multi_scale", "bottleneck")),
            Option("mixture_of_paths", "Each token routes through different layer subsets",
                   tags=("dynamic_routing", "sparse_compute")),
            Option("feedback_loop", "Feedback connections from later to earlier layers",
                   tags=("recurrent", "feedback")),
        ),
    ),

    # 7. NORMALIZATION — how activations are normalized
    Dimension(
        name="normalization",
        description="Normalization strategy",
        options=(
            Option("rmsnorm_pre", "Pre-norm RMSNorm (baseline)",
                   tags=("standard",)),
            Option("layernorm_pre", "Pre-norm LayerNorm",
                   tags=("standard",)),
            Option("no_norm", "No normalization (rely on careful init)",
                   tags=("minimal", "risky")),
            Option("dynamic_norm", "Learned per-token normalization scale",
                   tags=("dynamic",)),
            Option("group_norm", "Group normalization across channel groups",
                   tags=("group",)),
            Option("sigmoid_norm", "Sigmoid-gated normalization (QK-norm style)",
                   tags=("gated",)),
        ),
    ),

    # 8. POSITIONAL ENCODING — how position information is injected
    Dimension(
        name="positional_encoding",
        description="How position information is represented",
        options=(
            Option("rope", "Rotary Position Embeddings (baseline)",
                   tags=("standard", "relative")),
            Option("alibi", "ALiBi: learned linear bias on attention scores",
                   tags=("relative", "linear_bias")),
            Option("none", "No explicit position encoding",
                   tags=("minimal",)),
            Option("learned_absolute", "Learned absolute position embeddings",
                   tags=("absolute",)),
            Option("random_fourier", "Random Fourier features for position",
                   tags=("random", "relative")),
            Option("convolutional", "Position from causal convolutions (implicit)",
                   tags=("implicit", "conv")),
        ),
    ),
)

DIMENSION_NAMES = tuple(d.name for d in DIMENSIONS)

# Pre-built lookup dicts for O(1) dimension/option access
_DIMENSION_MAP: Dict[str, Dimension] = {d.name: d for d in DIMENSIONS}
_OPTION_MAP: Dict[str, Dict[str, Option]] = {
    d.name: {o.name: o for o in d.options} for d in DIMENSIONS
}


# ── Architecture Specification ─────────────────────────────────────────

@dataclass
class ArchSpec:
    """A complete architecture specification from one morphological roll."""
    choices: Dict[str, str]  # dimension_name -> option_name
    seed: int
    generation: int = 0  # which generation/batch this came from
    parent_id: Optional[str] = None  # if mutated from another spec

    @property
    def id(self) -> str:
        """Deterministic hash ID from choices."""
        key = json.dumps(self.choices, sort_keys=True)
        return hashlib.sha256(key.encode()).hexdigest()[:12]

    @property
    def short_name(self) -> str:
        """Human-readable short name."""
        parts = []
        for dim_name in DIMENSION_NAMES:
            opt = self.choices.get(dim_name, "?")
            # Take first letter of each word
            abbrev = "".join(w[0].upper() for w in opt.split("_"))
            parts.append(abbrev)
        return "-".join(parts)

    def get_option(self, dimension: str) -> Option:
        """Get the full Option object for a dimension."""
        opt_name = self.choices[dimension]
        dim_opts = _OPTION_MAP.get(dimension)
        if dim_opts:
            opt = dim_opts.get(opt_name)
            if opt is not None:
                return opt
        raise KeyError(f"No option '{opt_name}' in dimension '{dimension}'")

    def all_tags(self) -> set:
        """Collect all tags from all chosen options."""
        tags = set()
        for dim_name in self.choices:
            try:
                opt = self.get_option(dim_name)
                tags.update(opt.tags)
            except KeyError:
                pass
        return tags

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "short_name": self.short_name,
            "choices": self.choices,
            "seed": self.seed,
            "generation": self.generation,
            "parent_id": self.parent_id,
        }


# ── Constraint Filter ──────────────────────────────────────────────────

def _check_tag_incompatibilities(spec: ArchSpec) -> Optional[str]:
    """Check if any option's incompatible_with tags clash with other options' tags."""
    option_cache: Dict[str, Option] = {
        dim_name: spec.get_option(dim_name) for dim_name in spec.choices
    }
    tag_sources: Dict[str, List[Tuple[str, str]]] = {}
    for dim_name, opt in option_cache.items():
        for tag in opt.tags:
            tag_sources.setdefault(tag, []).append((dim_name, opt.name))

    for dim_name, opt_name in spec.choices.items():
        opt = option_cache[dim_name]
        if not opt.incompatible_with:
            continue
        for bad_tag in opt.incompatible_with:
            for other_dim, other_name in tag_sources.get(bad_tag, []):
                if other_dim == dim_name:
                    continue
                return (f"{dim_name}={opt_name} incompatible with "
                        f"{other_dim}={other_name} (tags: {{{bad_tag}}})")
    return None


def _check_structural_constraints(spec: ArchSpec) -> Optional[str]:
    """Hard constraints that prevent nonsensical combinations."""
    c = spec.choices

    # Binary/quantized tokens + hypernetwork weights = unstable gradients
    if c["token_representation"] in ("binary_hash", "residual_quantized"):
        if c["weight_storage"] == "hypernetwork":
            return "binary/quantized tokens + hypernetwork weights: gradient flow too fragile"

    # No normalization + complex/quaternion = likely to diverge
    if c["normalization"] == "no_norm":
        if c["token_representation"] in ("complex_valued", "quaternion"):
            return "no normalization + complex representations: will diverge"

    # Identity channel mixing + identity compute routing = literally nothing
    if c["channel_mixing"] == "identity_skip" and c["compute_routing"] == "uniform":
        if c["token_mixing"] == "conv_only":
            return "conv-only mixing + identity MLP + uniform routing: too minimal"

    # State space + graph attention = conflicting paradigms
    if c["token_mixing"] == "state_space" and c["topology"] == "dense_net":
        return "SSM + DenseNet: SSM is inherently sequential, DenseNet adds O(n^2) connections"

    # Feedback loop + early exit = contradictory
    if c["topology"] == "feedback_loop" and c["compute_routing"] == "early_exit":
        return "feedback loops + early exit: contradictory (can't exit if looping back)"

    return None


def is_valid_spec(spec: ArchSpec) -> Tuple[bool, Optional[str]]:
    """Check if an architecture spec passes all constraints."""
    reason = _check_tag_incompatibilities(spec)
    if reason:
        return False, reason

    reason = _check_structural_constraints(spec)
    if reason:
        return False, reason

    return True, None


# ── Dice Roller ────────────────────────────────────────────────────────

def roll(
    seed: Optional[int] = None,
    generation: int = 0,
    fixed: Optional[Dict[str, str]] = None,
    max_retries: int = 100,
) -> ArchSpec:
    """
    Roll the morphological dice to generate a random architecture spec.

    Args:
        seed: Random seed (None for random)
        generation: Generation number for tracking
        fixed: Dict of dimension_name -> option_name to fix (not randomized)
        max_retries: Max attempts to find a valid combination

    Returns:
        A valid ArchSpec

    Raises:
        RuntimeError if no valid combination found in max_retries
    """
    if seed is None:
        seed = random.randint(0, 2**32 - 1)

    rng = random.Random(seed)
    fixed = fixed or {}

    for attempt in range(max_retries):
        choices = {}
        for dim in DIMENSIONS:
            if dim.name in fixed:
                choices[dim.name] = fixed[dim.name]
            else:
                choices[dim.name] = dim.random_option(rng).name

        spec = ArchSpec(
            choices=choices,
            seed=seed + attempt,  # vary seed on retry
            generation=generation,
        )

        valid, reason = is_valid_spec(spec)
        if valid:
            return spec

    raise RuntimeError(f"No valid combination found in {max_retries} retries")


def mutate(
    spec: ArchSpec,
    n_mutations: int = 1,
    seed: Optional[int] = None,
    generation: int = 0,
    max_retries: int = 100,
) -> ArchSpec:
    """
    Mutate an existing spec by changing N random dimensions.

    Args:
        spec: The parent spec to mutate
        n_mutations: Number of dimensions to change
        seed: Random seed
        generation: Generation number
        max_retries: Max attempts to find valid mutation

    Returns:
        A new valid ArchSpec with parent_id set
    """
    if seed is None:
        seed = random.randint(0, 2**32 - 1)

    rng = random.Random(seed)
    n_mutations = min(n_mutations, len(DIMENSIONS))

    for attempt in range(max_retries):
        new_choices = dict(spec.choices)
        dims_to_mutate = rng.sample(DIMENSION_NAMES, n_mutations)

        for dim_name in dims_to_mutate:
            for dim in DIMENSIONS:
                if dim.name == dim_name:
                    # Pick a DIFFERENT option than current
                    current = new_choices[dim_name]
                    candidates = [o for o in dim.options if o.name != current]
                    if candidates:
                        new_choices[dim_name] = rng.choice(candidates).name
                    break

        new_spec = ArchSpec(
            choices=new_choices,
            seed=seed + attempt,
            generation=generation,
            parent_id=spec.id,
        )

        valid, reason = is_valid_spec(new_spec)
        if valid:
            return new_spec

    raise RuntimeError(f"No valid mutation found in {max_retries} retries")


def crossover(
    spec_a: ArchSpec,
    spec_b: ArchSpec,
    seed: Optional[int] = None,
    generation: int = 0,
    max_retries: int = 100,
) -> ArchSpec:
    """
    Crossover two specs: randomly pick each dimension from one parent.

    Returns:
        A new valid ArchSpec
    """
    if seed is None:
        seed = random.randint(0, 2**32 - 1)

    rng = random.Random(seed)

    for attempt in range(max_retries):
        choices = {}
        for dim_name in DIMENSION_NAMES:
            if rng.random() < 0.5:
                choices[dim_name] = spec_a.choices[dim_name]
            else:
                choices[dim_name] = spec_b.choices[dim_name]

        new_spec = ArchSpec(
            choices=choices,
            seed=seed + attempt,
            generation=generation,
            parent_id=f"{spec_a.id}x{spec_b.id}",
        )

        valid, reason = is_valid_spec(new_spec)
        if valid:
            return new_spec

    raise RuntimeError(f"No valid crossover found in {max_retries} retries")


def batch_roll(
    n: int,
    generation: int = 0,
    fixed: Optional[Dict[str, str]] = None,
    base_seed: Optional[int] = None,
) -> List[ArchSpec]:
    """Generate N unique valid architecture specs."""
    if base_seed is None:
        base_seed = random.randint(0, 2**32 - 1)

    specs = []
    seen_ids = set()
    seed = base_seed

    while len(specs) < n:
        spec = roll(seed=seed, generation=generation, fixed=fixed)
        if spec.id not in seen_ids:
            specs.append(spec)
            seen_ids.add(spec.id)
        seed += 1000  # jump ahead to avoid correlation

    return specs


# ── Pretty Print ───────────────────────────────────────────────────────

def describe_spec(spec: ArchSpec) -> str:
    """Pretty-print an architecture spec."""
    lines = [f"Architecture {spec.id} (seed={spec.seed}, gen={spec.generation})"]
    if spec.parent_id:
        lines.append(f"  Parent: {spec.parent_id}")
    lines.append(f"  Name: {spec.short_name}")
    lines.append("")

    for dim in DIMENSIONS:
        opt_name = spec.choices.get(dim.name, "?")
        opt = spec.get_option(dim.name)
        marker = " *" if "standard" not in opt.tags else ""
        lines.append(f"  {dim.name:25s} = {opt_name:30s}{marker}")
        lines.append(f"  {'':25s}   {opt.description}")

    lines.append("")
    lines.append(f"  Tags: {', '.join(sorted(spec.all_tags()))}")
    return "\n".join(lines)


if __name__ == "__main__":
    # Demo: roll 5 random architectures
    import sys
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 5

    print(f"Rolling {n} random architectures...\n")
    specs = batch_roll(n, generation=0)
    for spec in specs:
        print(describe_spec(spec))
        print("=" * 80)
