export const LEADERBOARD_PREFS_KEY = 'aria_leaderboard_prefs_v1';

export const COLUMNS = [
  {
    key: '_score',
    label: 'Score',
    title: 'Canonical active scorer total. Colors use fixed 15/30/45/60/75/90% rubric bands.',
  },
  {
    key: '_capability_quality',
    label: 'Capability',
    title: 'Capability quality separate from workflow completion: Capability-Qualified, Training-Only, Validation Pending, etc.',
  },
  { key: 'tier', label: 'Tier', title: "The model's current research phase: Screening, Investigation, Validation, or Breakthrough." },
  { key: '_verified', label: 'Eval', title: 'Evaluation provenance: trusted BPE, partial BPE, legacy, or missing.' },
  { key: '_rate', label: 'Rate', title: '2K-6K loss improvement rate. Green >10%, yellow 5-10%, red <5%.' },
  { key: '_gap', label: 'Gap', title: 'Gap vs GPT-2 in nats (negative = beats GPT-2).' },
  { key: '_stability', label: 'Stability', title: "Tracks how the model's rank has changed over recent experiments." },
  { key: 'model_source', label: 'Source', title: 'The method used to generate this model (e.g., Graph Synthesis or Morphological Box).' },
  { key: 'architecture_family', label: 'Family', title: 'Architectural category like Attention, SSM, or Hybrid.' },
  { key: 'architecture_desc', label: 'Description', title: 'Human-readable summary or reference name.' },
  { key: '_composition', label: 'Composition', title: 'Architectural blocks and templates used to construct this layer.' },
  { key: '_vs_reference', label: 'vs Ref Loss', title: 'Percentage of the loss achieved by the nearest frontier baseline (lower is better).' },
  { key: 'composite_score', label: 'Composite', title: 'Canonical active scorer composite. Performance + convergence + efficiency + novelty + robustness + capability + understanding.' },
  { key: 'discovery_loss_ratio', label: 'D.Loss', title: 'Loss ratio on random tokens (discovery phase).' },
  { key: 'validation_loss_ratio', label: 'V.Loss', title: 'Validation loss ratio on micro-corpus (Stage 1 or higher).' },
  { key: 'moe_routing_efficiency', label: 'MoE Eff', title: 'Mixture of Experts routing efficiency (higher is more selective).' },
  { key: 'arch_quality_score', label: 'Arch Q', title: 'Structural Intelligence Score (0-1). Rewards coherent patterns like Attention+RoPE and Adaptive Routing.' },
  { key: 'screening_loss_ratio', label: 'S.Loss', title: 'Tiered loss ratio from the initial screening phase (Legacy or Rescored).' },
  { key: 'screening_novelty', label: 'Novelty', title: 'How different this architecture is from known patterns (0-1).' },
  { key: 'investigation_loss_ratio', label: 'I.Loss', title: 'Loss ratio from the deeper investigation phase.' },
  { key: 'investigation_robustness', label: 'Robust', title: 'Fraction of training recipes that succeed (higher is more stable).' },
  { key: 'validation_baseline_ratio', label: 'V.Base', title: 'Final loss compared to a fixed baseline; < 1.0 means it beats the baseline.' },
  { key: 'robustness_noise_score', label: 'Noise', title: 'Sensitivity to input noise (lower is more robust).' },
  { key: 'quant_int8_retention', label: 'INT8 Ret', title: 'Performance preserved after INT8 quantization (higher is better).' },
  { key: 'robustness_long_ctx_score', label: 'LongCtx', title: 'Scaling performance on longer sequences (higher is better).' },
  { key: 'robustness_long_ctx_scaling_score', label: 'LC-Scale', title: 'Long-context scaling component score.' },
  { key: 'robustness_long_ctx_assoc_score', label: 'LC-Assoc', title: 'Associative retrieval benchmark score.' },
  { key: 'robustness_long_ctx_multi_hop_score', label: 'LC-MHop', title: 'Multi-hop retrieval benchmark score.' },
  { key: 'robustness_long_ctx_passkey_score', label: 'LC-Passkey', title: 'Zero-shot passkey retrieval benchmark score.' },
  { key: 'robustness_long_ctx_retrieval_aggregate', label: 'LC-Retr', title: 'Aggregate retrieval score across long-context benchmarks.' },
  { key: 'robustness_long_ctx_combined_score', label: 'LC-Comb', title: 'Final long-context combined score used by evaluation.' },
  { key: 'champion_tiny_model_score', label: 'Champ Score', title: 'Champion tiny-model protocol total score out of 50.' },
  { key: 'champion_tiny_model_protocol_version', label: 'Champ Ver', title: 'Champion tiny-model scoring protocol version.' },
  { key: 'champion_hard_failure_reason', label: 'Champ Fail', title: 'Champion tiny-model hard-failure reason, if any.' },
  { key: 'champion_steps_to_floor', label: 'Floor @', title: 'Training step where the smoothed loss first reached the detected floor band.' },
  { key: 'champion_floor_loss', label: 'Floor CE', title: 'Detected champion-mode floor cross-entropy loss.' },
  { key: 'champion_floor_ppl', label: 'Floor PPL', title: 'Perplexity derived from the detected champion-mode floor loss.' },
  { key: 'champion_floor_loss_std', label: 'Floor Std', title: 'Post-floor loss standard deviation used as champion-mode stability evidence.' },
  { key: 'champion_plateau_detected_step', label: 'Plateau @', title: 'Step where plateau detection triggered for champion-mode floor extraction.' },
  { key: 'champion_plateau_window', label: 'Plateau Win', title: 'Window size used by the champion-mode plateau detector.' },
  { key: 'champion_floor_protocol_version', label: 'Floor Ver', title: 'Champion floor extraction protocol version.' },
  { key: 'champion_baseline_result_id', label: 'Base RID', title: 'GPT-2 neutral-control result used for champion tiny-model scoring.' },
  { key: 'champion_baseline_layers', label: 'Base L', title: 'Layer count of the GPT-2 neutral-control baseline.' },
  { key: 'champion_baseline_protocol_version', label: 'Base Ver', title: 'Baseline lookup protocol version for champion tiny-model scoring.' },
  { key: 'champion_steps_to_floor_score', label: 'Floor Spd', title: 'Champion score component for reaching the training floor quickly.' },
  { key: 'champion_floor_quality_score', label: 'Floor Q', title: 'Champion score component for floor quality or best PPL.' },
  { key: 'champion_floor_stability_score', label: 'Floor Stab', title: 'Champion score component for post-floor stability.' },
  { key: 'champion_induction_validation_score', label: 'Champ Ind VAL', title: 'Champion score component from induction v3 evidence.' },
  { key: 'champion_binding_long_context_score', label: 'Bind/LC', title: 'Champion score component from binding v2 and long-context capability evidence.' },
  { key: 'champion_ar_validation_score', label: 'Champ AR VAL', title: 'Champion score component from the AR validation champion probe.' },
  { key: 'max_viable_seq_len', label: 'LC-MaxLen', title: 'Maximum viable sequence length from long-context scaling sweep.' },
  { key: 'init_sensitivity_std', label: 'InitStd', title: 'Sensitivity to weight initialization variance (lower is better).' },
  { key: 'pre_inv_score', label: 'Readiness', title: 'Pre-investigation gate readiness score (0-100). Higher means more likely to succeed in investigation.' },
  { key: 'jacobian_spectral_norm', label: 'Spectral', title: 'Jacobian Spectral Norm: measures gradient explosion risk (lower is more stable).' },
  { key: 'fp_jacobian_effective_rank', label: 'JRank', title: 'Jacobian effective rank from the fingerprint pass. Higher means broader sensitivity structure.' },
  { key: 'fp_sensitivity_uniformity', label: 'SensUnif', title: 'Uniformity of sensitivity across inputs/operators from fingerprinting.' },
  { key: 'fp_jacobian_erf_density', label: 'ERF Dens', title: 'Effective receptive-field density. Strongest observed capability predictor: Spearman rho +0.561 vs binding v2 AUC, +0.339 vs induction v2 AUC.' },
  { key: 'fp_id_collapse_rate', label: 'ID Collapse', title: 'Intrinsic-dimension collapse rate during training. Strong binding signal: Spearman rho +0.556 vs binding v2 AUC. Sparse but meaningful.' },
  { key: 'fp_id_collapse_rate_normalized', label: 'ID CollN', title: 'Normalized intrinsic-dimension collapse rate. More populated companion to raw ID collapse.' },
  { key: 'fp_jacobian_erf_decay_slope', label: 'ERF Decay', title: 'How influence decays with distance. Moderate capability signal: rho +0.281 vs binding v2, +0.314 vs induction v2.' },
  { key: 'fp_jacobian_erf_first_norm', label: 'ERF First', title: 'ERF norm at the first input position.' },
  { key: 'fp_jacobian_erf_last_norm', label: 'ERF Last', title: 'ERF norm at the last input position.' },
  { key: 'fp_logit_margin_velocity', label: 'Margin Vel', title: 'Logit-margin velocity. Weak positive capability signal: rho +0.180 vs binding v2.' },
  { key: 'fp_logit_margin_delta', label: 'Margin Δ', title: 'Total logit-margin change during the fingerprint trajectory.' },
  { key: 'fp_jacobian_erf_variance_log', label: 'ERF VarLog', title: 'Log-scaled ERF variance. Mild negative capability correlation; useful as a cautionary dispersion signal.' },
  { key: 'fp_jacobian_spectral_norm_log', label: 'SpecLog', title: 'Log-scaled Jacobian spectral norm. Correlates more with loss noise than capability; lower is generally safer.' },
  { key: 'fp_icld_velocity', label: 'ICLD Vel', title: 'ICLD velocity. Empirically near-noise for capability (rho +0.025 vs binding v2); included for audit, not promotion.' },
  { key: 'fp_icld_delta_loss', label: 'ICLD ΔLoss', title: 'ICLD early-to-late loss delta. Included for audit because ICLD velocity is empirically weak.' },
  { key: 'wikitext_ppl', label: 'PPL', title: 'Real-token capability measured on WikiText-2 (lower is better).' },
  { key: 'peak_ppl', label: 'Peak PPL', title: 'Best PPL seen at any checkpoint (lower is better).' },
  { key: 'divergence_step', label: 'Diverge @', title: 'Step where PPL diverges (>2x peak).' },
  { key: 'wikitext_ppl_trajectory', label: 'Trajectory', title: '4-point PPL trajectory (200 \u2192 500 \u2192 1000 \u2192 2000 steps).' },
  { key: 'evaluation_stage', label: 'Stage', title: 'Current evaluation depth: SCREENED, PROBED, ESCALATED, or FRONT_VALIDATED.' },
  { key: 'robustness_grade', label: 'Grade', title: 'Robustness grading (A: Robust, B: Stable, C: Fragile) based on training recipe success.' },
  { key: 'hellaswag_acc', label: 'HellaSwag', title: 'Commonsense reasoning accuracy (4-choice). 25% = random chance, 31% = GPT-2 Small. Informational only for champion/tiny-model mode.' },
  { key: 'induction_screening_auc', label: 'Ind SCRN', title: 'Induction head AUC across gap distances. Measures exact token retrieval — only full attention passes reliably. Mamba/RWKV ~0 is expected (different failure mechanism).' },
  { key: 'induction_intermediate_auc', label: 'Ind INTER', title: 'Investigation-tier induction probe (mixed-gap training, 500 steps, median-of-3 seeds). Cleaner architectural discriminator than the screening-tier v1 induction probe. NULL for screening-tier entries.' },
  { key: 'induction_validation_auc', label: 'Ind VAL', title: 'Champion-tier induction probe AUC using the v3 long-budget protocol.' },
  { key: 'induction_validation_max_gap_acc', label: 'Ind VAL Max', title: 'Best gap accuracy from champion-tier induction v3.' },
  { key: 'induction_validation_gap_accuracy_cv', label: 'Ind VAL CV', title: 'Coefficient of variation across induction v3 gap accuracies; lower is more consistent.' },
  { key: 'induction_validation_gap_accuracies_json', label: 'Ind VAL Gaps', title: 'Serialized gap-accuracy breakdown from induction v3.' },
  { key: 'induction_validation_steps_trained', label: 'Ind VAL Steps', title: 'Training steps used by the induction v3 probe.' },
  { key: 'induction_validation_status', label: 'Ind VAL Status', title: 'Execution status for the induction v3 probe.' },
  { key: 'induction_validation_elapsed_ms', label: 'Ind VAL ms', title: 'Elapsed runtime in milliseconds for the induction v3 probe.' },
  { key: 'induction_validation_protocol_version', label: 'Ind VAL Ver', title: 'Protocol version for the induction v3 probe.' },
  { key: 'ar_legacy_auc', label: 'AR Score', title: 'Full associative recall AUC. Visible for comparison, but informational only for champion/tiny-model mode.' },
  { key: 'ar_validation_rank_score', label: 'AR VAL', title: 'Champion-scale synthetic associative-recall score.' },
  { key: 'ar_validation_final_acc', label: 'AR VAL Fin', title: 'Final accuracy from the AR validation champion probe.' },
  { key: 'ar_validation_held_pair_acc', label: 'AR VAL Pair', title: 'Held-pair match accuracy from the AR validation champion probe.' },
  { key: 'ar_validation_held_class_acc', label: 'AR VAL Class', title: 'Held-class accuracy from the AR validation champion probe.' },
  { key: 'ar_validation_learning_curve_json', label: 'AR VAL Curve', title: 'Serialized learning curve from the AR validation champion probe.' },
  { key: 'ar_validation_steps_to_floor', label: 'AR VAL Floor', title: 'AR Validation champion probe steps to floor.' },
  { key: 'ar_validation_status', label: 'AR VAL Status', title: 'Execution status for the AR validation champion probe.' },
  { key: 'ar_validation_elapsed_ms', label: 'AR VAL ms', title: 'Elapsed runtime in milliseconds for the AR validation champion probe.' },
  { key: 'ar_validation_metric_version', label: 'AR VAL Ver', title: 'Metric version for the AR validation champion probe.' },
  { key: 'ar_curriculum_auc_pair_final', label: 'AR CUR AUC', title: 'AR Curriculum probe: mean held_pair_acc across 6 disjoint-token stages (S0–S5). Replaces ar_intermediate as the primary differentiation probe (Spearman ρ=1.0 vs ar_validation, 3.4× spread).' },
  { key: 'ar_curriculum_s0_retention', label: 'AR CUR Retain', title: 'AR Curriculum S0 retention: held_pair_acc on the easiest stage AFTER cumulative training through S5. Low value = catastrophic forgetting (e.g. dense attention, RAG). High value = retention-resistant (Mamba-class).' },
  { key: 'ar_curriculum_max_passing_stage', label: 'AR CUR Pass', title: 'Highest stage where held_pair_acc cleared 4× chance (−0 = no stage cleared, 5 = all 6 stages cleared).' },
  { key: 'ar_curriculum_per_stage_held_pair_acc', label: 'AR CUR Curve', title: 'JSON-encoded per-stage held_pair_acc array (S0..S5). Used by program detail view for the curriculum curve chart.' },
  { key: 'ar_curriculum_status', label: 'AR CUR Status', title: 'Execution status for the AR curriculum probe.' },
  { key: 'ar_curriculum_elapsed_ms', label: 'AR CUR ms', title: 'Elapsed runtime in milliseconds for the AR curriculum probe.' },
  { key: 'ar_curriculum_metric_version', label: 'AR CUR Ver', title: 'Metric version for the AR curriculum probe.' },
  { key: 'binding_screening_auc', label: 'Bind SCRN', title: 'Copy-at-distance AUC. Measures how far the model can copy tokens. Attention ~0.4+, SSM ~0.1-0.2, conv-3 ~0.01.' },
  { key: 'binding_intermediate_auc', label: 'Bind INTER', title: 'Investigation-tier binding probe (2400 steps, 5 distances incl. 64, median-of-3 seeds). Bumped training budget exposes depth-dependent capability the screening probe misses. NULL for screening-tier entries.' },
  { key: '_language_control_ladder', label: 'LC Ladder', title: 'Language-control v14 ladder: S05, S10, and INV tier scores from synthetic association and nano-BLiMP fields. Yellow ! marks INV SA below 0.85.' },
  { key: 'blimp_overall_accuracy', label: 'BLiMP', title: 'Linguistic minimal pairs accuracy. 50% = chance. Visible for comparison, but informational only for champion/tiny-model mode.' },
  { key: '_compression_ratio', label: 'Compression', title: 'Effective parameter reduction compared to a dense baseline.' },
  { key: '_metric_quality', label: 'Metric Quality', title: 'Reliability of recorded metrics based on evidence depth.' },
  { key: '_actions', label: 'Actions', title: 'Available research operations for this candidate.' },
];
