export const LEADERBOARD_PREFS_KEY = 'aria_leaderboard_prefs_v1';

export const COLUMNS = [
  {
    key: '_score',
    label: 'Score',
    title: 'Open-ended score anchored to GPT-2 = 100. Above 100 = beats GPT-2. No ceiling.',
  },
  { key: 'tier', label: 'Tier', title: "The model's current research phase: Screening, Investigation, Validation, or Breakthrough." },
  { key: '_verified', label: 'Verified', title: 'Verification status: tiktoken+wikitext103, tiktoken only, or byte-era.' },
  { key: '_rate', label: 'Rate', title: '2K-6K loss improvement rate. Green >10%, yellow 5-10%, red <5%.' },
  { key: '_gap', label: 'Gap', title: 'Gap vs GPT-2 in nats (negative = beats GPT-2).' },
  { key: '_stability', label: 'Stability', title: "Tracks how the model's rank has changed over recent experiments." },
  { key: 'model_source', label: 'Source', title: 'The method used to generate this model (e.g., Graph Synthesis or Morphological Box).' },
  { key: 'architecture_family', label: 'Family', title: 'Architectural category like Attention, SSM, or Hybrid.' },
  { key: 'architecture_desc', label: 'Description', title: 'Human-readable summary or reference name.' },
  { key: '_composition', label: 'Composition', title: 'Architectural blocks and templates used to construct this layer.' },
  { key: '_vs_reference', label: 'vs Ref Loss', title: 'Percentage of the loss achieved by the nearest frontier baseline (lower is better).' },
  { key: 'composite_score', label: 'Composite', title: 'v6 composite: GPT-2 = 100 anchor, open-ended. Performance (60%) + convergence (20%) + efficiency (10%) + novelty (5%) + robustness (5%).' },
  { key: 'discovery_loss_ratio', label: 'D.Loss', title: 'Loss ratio on random tokens (discovery phase).' },
  { key: 'validation_loss_ratio', label: 'V.Loss', title: 'Validation loss ratio on micro-corpus (Stage 1 or higher).' },
  { key: 'moe_routing_efficiency', label: 'MoE Eff', title: 'Mixture of Experts routing efficiency (higher is more selective).' },
  { key: 'arch_quality_score', label: 'Arch Q', title: 'Structural Intelligence Score (0-1). Rewards coherent patterns like Attention+RoPE and Adaptive Routing.' },
  { key: 'screening_loss_ratio', label: 'S.Loss', title: 'Tiered loss ratio from the initial screening phase (Legacy or Rescored).' },
  { key: 'screening_novelty', label: 'Novelty', title: 'How different this architecture is from known patterns (0-1).' },
  { key: 'investigation_loss_ratio', label: 'I.Loss', title: 'Loss ratio from the deeper investigation phase.' },
  { key: 'investigation_robustness', label: 'Robust', title: 'Fraction of training recipes that succeed (higher is more stable).' },
  { key: 'validation_baseline_ratio', label: 'V.Base', title: 'Final loss compared to a fixed baseline; < 1.0 means it beats the baseline.' },
  { key: 'robustness_noise_score', label: 'Noise', title: 'Sensitivity to input noise (lower is more robust).' },
  { key: 'quant_int8_retention', label: 'INT8 Ret', title: 'Performance preserved after INT8 quantization (higher is better).' },
  { key: 'robustness_long_ctx_score', label: 'LongCtx', title: 'Scaling performance on longer sequences (higher is better).' },
  { key: 'robustness_long_ctx_scaling_score', label: 'LC-Scale', title: 'Long-context scaling component score.' },
  { key: 'robustness_long_ctx_assoc_score', label: 'LC-Assoc', title: 'Associative retrieval benchmark score.' },
  { key: 'robustness_long_ctx_multi_hop_score', label: 'LC-MHop', title: 'Multi-hop retrieval benchmark score.' },
  { key: 'robustness_long_ctx_passkey_score', label: 'LC-Passkey', title: 'Zero-shot passkey retrieval benchmark score.' },
  { key: 'robustness_long_ctx_retrieval_aggregate', label: 'LC-Retr', title: 'Aggregate retrieval score across long-context benchmarks.' },
  { key: 'robustness_long_ctx_combined_score', label: 'LC-Comb', title: 'Final long-context combined score used by evaluation.' },
  { key: 'max_viable_seq_len', label: 'LC-MaxLen', title: 'Maximum viable sequence length from long-context scaling sweep.' },
  { key: 'init_sensitivity_std', label: 'InitStd', title: 'Sensitivity to weight initialization variance (lower is better).' },
  { key: 'pre_inv_score', label: 'Readiness', title: 'Pre-investigation gate readiness score (0-100). Higher means more likely to succeed in investigation.' },
  { key: 'jacobian_spectral_norm', label: 'Spectral', title: 'Jacobian Spectral Norm: measures gradient explosion risk (lower is more stable).' },
  { key: 'wikitext_ppl', label: 'PPL', title: 'Real-token capability measured on WikiText-2 (lower is better).' },
  { key: 'peak_ppl', label: 'Peak PPL', title: 'Best PPL seen at any checkpoint (lower is better).' },
  { key: 'divergence_step', label: 'Diverge @', title: 'Step where PPL diverges (>2x peak).' },
  { key: 'wikitext_ppl_trajectory', label: 'Trajectory', title: '4-point PPL trajectory (200 \u2192 500 \u2192 1000 \u2192 2000 steps).' },
  { key: 'evaluation_stage', label: 'Stage', title: 'Current evaluation depth: SCREENED, PROBED, ESCALATED, or FRONT_VALIDATED.' },
  { key: 'robustness_grade', label: 'Grade', title: 'Robustness grading (A: Robust, B: Stable, C: Fragile) based on training recipe success.' },
  { key: 'hellaswag_acc', label: 'HellaSwag', title: 'Commonsense reasoning accuracy (4-choice). 25% = random chance, 31% = GPT-2 Small. Informational only at nano scale.' },
  { key: 'induction_auc', label: 'Induction', title: 'Induction head AUC across gap distances. Measures exact token retrieval — only full attention passes reliably. Mamba/RWKV ~0 is expected (different failure mechanism).' },
  { key: 'ar_auc', label: 'AR Score', title: 'Associative Recall AUC. Measures key-value binding across positions. Higher = stronger non-local memory.' },
  { key: 'binding_auc', label: 'Binding', title: 'Copy-at-distance AUC. Measures how far the model can copy tokens. Attention ~0.4+, SSM ~0.1-0.2, conv-3 ~0.01.' },
  { key: 'blimp_overall_accuracy', label: 'BLiMP', title: 'Linguistic minimal pairs accuracy. 50% = chance. Measures grammatical knowledge across 67 subtasks (agreement, binding, control, etc.).' },
  { key: '_compression_ratio', label: 'Compression', title: 'Effective parameter reduction compared to a dense baseline.' },
  { key: '_metric_quality', label: 'Metric Quality', title: 'Reliability of recorded metrics based on evidence depth.' },
  { key: '_actions', label: 'Actions', title: 'Available research operations for this candidate.' },
];
