"""Component proposers — turn corpus signal into candidate component specs."""

from .property_miner import (
    AxisLift,
    CandidateTuple,
    DEFAULT_AXES,
    DEFAULT_META_DB,
    compute_axis_lifts,
    enumerate_candidates,
    extant_tuples,
    load_rows,
    run,
)
from .spec_generator import (
    CATEGORY_COMPRESSION,
    CATEGORY_LANE,
    CATEGORY_ROUTING,
    ProposalSpec,
    SYNTHESIS_KIND_BASIS_SWAP,
    SYNTHESIS_KIND_NOVEL_HYBRID,
    SYNTHESIS_KIND_PROJECTION_SWAP,
    SYNTHESIS_KIND_SEMIRING_SWAP,
    SYNTHESIS_KIND_STATE_KERNEL_SWAP,
    category_from_axes,
    spec_from_candidate,
    spec_to_json,
    specs_from_candidates,
    synthesis_kind_for_axes,
)

__all__ = [
    "AxisLift",
    "CATEGORY_COMPRESSION",
    "CATEGORY_LANE",
    "CATEGORY_ROUTING",
    "CandidateTuple",
    "DEFAULT_AXES",
    "DEFAULT_META_DB",
    "ProposalSpec",
    "SYNTHESIS_KIND_BASIS_SWAP",
    "SYNTHESIS_KIND_NOVEL_HYBRID",
    "SYNTHESIS_KIND_PROJECTION_SWAP",
    "SYNTHESIS_KIND_SEMIRING_SWAP",
    "SYNTHESIS_KIND_STATE_KERNEL_SWAP",
    "category_from_axes",
    "compute_axis_lifts",
    "enumerate_candidates",
    "extant_tuples",
    "load_rows",
    "run",
    "spec_from_candidate",
    "spec_to_json",
    "specs_from_candidates",
    "synthesis_kind_for_axes",
]
