"""Tests for under-observed component reachability and compilation.

Verifies that every under-observed op can be:
1. Generated by the grammar in exploration mode
2. Compiled into a valid model
3. Run a forward pass without NaN/Inf
"""

import pytest
import torch
from collections import Counter

from research.synthesis.grammar import GrammarConfig, generate_layer_graph
from research.synthesis.compiler import compile_model
from research.synthesis.context_rules import find_graph_context_violations
from research.synthesis.op_roles import get_role, OpRole
from research.tools.explore_under_observed import generate_forced_graph


# All ops with <20 historical observations
UNDER_OBSERVED_OPS = frozenset(
    [
        "learned_token_gate",
        "cumprod_safe",
        "confidence_token_gate",
        "depth_token_mask",
        "reciprocal",
        "split3",
        "sparse_bottleneck_moe",
        "sparse_threshold",
        "stdp_attention",
        "max_last",
        "kronecker_linear",
        "mean_last",
        "sum_last",
        "padic_gate",
        "log",
        "sign_ste",
        "chebyshev_spectral_mix",
        "maximum",
        "poincare_add",
        "geometric_product",
        "norm_last",
        "cumsum",
        "sqrt",
        "tropical_matmul",
        "div_safe",
        "minimum",
        "sub",
        "lif_neuron",
        "spike_rate_code",
        "exp",
        "hyp_distance",
        "shared_basis_proj",
        "tropical_moe",
        "tropical_router",
        "hyperbolic_norm",
        "hyp_linear",
        "hyp_tangent_nonlinear",
        "grouped_linear",
        "fixed_point_iter",
        "adjacent_token_merge",
        "bottleneck_proj",
        "rotor_transform",
        "outer_product",
    ]
)


@pytest.mark.unit
class TestRoleFixes:
    """Verify role mapping fixes for previously-broken ops."""

    def test_n_way_sparse_router_is_route(self):
        assert get_role("sparse_bottleneck_moe") == OpRole.ROUTE

    def test_cumprod_safe_is_reduce(self):
        assert get_role("cumprod_safe") == OpRole.REDUCE

    def test_embedding_lookup_is_project(self):
        """embedding_lookup redesigned as learnable codebook projection."""
        assert get_role("embedding_lookup") == OpRole.PROJECT


@pytest.mark.unit
class TestExplorationConfig:
    """Verify GrammarConfig.exploration() works correctly."""

    def test_exploration_config_creation(self):
        targets = frozenset(["learned_token_gate", "confidence_token_gate"])
        config = GrammarConfig.exploration(targets)
        assert config.exploration_targets == targets
        assert config.exploration_boost_factor == 4.0

    def test_exploration_config_custom_boost(self):
        config = GrammarConfig.exploration(
            frozenset(["learned_token_gate"]), boost_factor=10.0
        )
        assert config.exploration_boost_factor == 10.0

    def test_exploration_generates_valid_graphs(self):
        config = GrammarConfig.exploration(
            frozenset(["cumprod_safe", "div_safe"]), boost_factor=8.0
        )
        generated = 0
        for seed in range(50):
            try:
                generate_layer_graph(config, seed=seed)
                generated += 1
            except ValueError:
                pass
        assert generated > 20, f"Only {generated}/50 graphs generated"

    @pytest.mark.parametrize("op_name", ["sparse_threshold", "stdp_attention"])
    def test_forced_generation_covers_spiking_threshold_and_stdp(self, op_name):
        graph, retries = generate_forced_graph(op_name, seed=42, max_retries=50)
        assert graph is not None, f"{op_name} never generated after {retries} retries"
        ops = {
            n.op_name
            for n in graph.nodes.values()
            if n.op_name not in ("input", "output")
        }
        assert op_name in ops, graph.to_dict()

    @pytest.mark.parametrize("op_name", ["local_window_attn", "sparse_bottleneck_moe"])
    def test_forced_generation_uses_multiple_valid_wrapper_variants(self, op_name):
        fingerprints = set()
        for seed in (42, 43, 44):
            graph, retries = generate_forced_graph(op_name, seed=seed, max_retries=10)
            assert graph is not None, (
                f"{op_name} never generated after {retries} retries"
            )
            ops = {
                n.op_name
                for n in graph.nodes.values()
                if n.op_name not in ("input", "output")
            }
            assert op_name in ops, graph.to_dict()
            assert find_graph_context_violations(graph) == [], graph.to_dict()
            fingerprints.add(graph.fingerprint())

        assert len(fingerprints) >= 2, f"{op_name} only produced one forced wrapper"


@pytest.mark.pipeline
class TestCompileForward:
    """Verify each under-observed op compiles and forwards correctly.

    Uses exploration mode with high boost to maximize target op selection.
    Accepts if at least 80% of selected ops appear in 500 seeds.
    """

    @pytest.fixture(scope="class")
    def compile_forward_results(self):
        """Run bulk graph generation once, share results across tests."""
        config = GrammarConfig.exploration(UNDER_OBSERVED_OPS, boost_factor=8.0)
        compile_ok = Counter()
        forward_ok = Counter()

        for seed in range(300):
            try:
                g = generate_layer_graph(config, seed=seed)
            except (ValueError, Exception):
                continue
            ops = {
                n.op_name
                for n in g.nodes.values()
                if n.op_name not in ("input", "output")
            }
            hits = ops & UNDER_OBSERVED_OPS
            if not hits:
                continue
            try:
                model = compile_model([g], vocab_size=1000)
                for op in hits:
                    compile_ok[op] += 1
            except Exception:
                continue
            try:
                x = torch.randint(0, 1000, (2, 32))
                with torch.no_grad():
                    out = model(x)
                ok = not (torch.isnan(out).any() or torch.isinf(out).any())
                if ok:
                    for op in hits:
                        forward_ok[op] += 1
            except Exception:
                pass

        return compile_ok, forward_ok

    def test_most_ops_generated(self, compile_forward_results):
        compile_ok, _ = compile_forward_results
        generated = set(compile_ok.keys())
        coverage = len(generated) / len(UNDER_OBSERVED_OPS)
        assert coverage >= 0.7, (
            f"Only {len(generated)}/{len(UNDER_OBSERVED_OPS)} ops generated. "
            f"Missing: {sorted(UNDER_OBSERVED_OPS - generated)}"
        )

    def test_all_compiled_ops_forward(self, compile_forward_results):
        compile_ok, forward_ok = compile_forward_results
        for op in compile_ok:
            c = compile_ok[op]
            f = forward_ok.get(op, 0)
            rate = f / c if c > 0 else 0
            assert rate >= 0.8, f"{op}: forward pass rate {f}/{c} = {rate:.0%} < 80%"

    def test_no_nan_inf_outputs(self, compile_forward_results):
        """All forward passes must produce finite outputs."""
        compile_ok, forward_ok = compile_forward_results
        for op in compile_ok:
            c = compile_ok[op]
            f = forward_ok.get(op, 0)
            # If any compilation succeeded, at least one must forward cleanly
            if c > 0:
                assert f > 0, f"{op}: compiled {c} times but no clean forward"


@pytest.mark.unit
class TestSplitContiguity:
    """Regression test: split ops must return contiguous tensors."""

    def test_split2_contiguous(self):
        from research.synthesis.compiler_ops_math import _op_split2

        x = torch.randn(2, 32, 256)
        for part in (0, 1):
            out = _op_split2(None, (x,), {"part": part})
            assert out.is_contiguous(), f"split2 part={part} not contiguous"

    def test_split3_contiguous(self):
        from research.synthesis.compiler_ops_math import _op_split3

        x = torch.randn(2, 32, 258)  # divisible by 3
        for part in (0, 1, 2):
            out = _op_split3(None, (x,), {"part": part})
            assert out.is_contiguous(), f"split3 part={part} not contiguous"


@pytest.mark.unit
class TestTropicalMatmulShape:
    """Regression test: tropical_matmul must return (B, S, S) not (B, S, D)."""

    def test_tropical_matmul_shape(self):
        from research.mathspaces.tropical import tropical_matmul

        a = torch.randn(2, 32, 256)
        b = torch.randn(2, 32, 256)
        with torch.no_grad():
            result = tropical_matmul(a, b)
        assert result.shape == (2, 32, 32), f"Expected (2, 32, 32), got {result.shape}"
