from __future__ import annotations

import sqlite3
from pathlib import Path

from research.scientist.discovery_scoring import discovery_score
from research.tools.rescreen_leaderboard_batch import _select_candidates


def _init_schema(db_path: Path) -> None:
    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(
            """
            CREATE TABLE leaderboard (
                entry_id TEXT PRIMARY KEY,
                result_id TEXT,
                composite_score REAL,
                tier TEXT,
                investigation_loss_ratio REAL,
                screening_loss_ratio REAL,
                validation_baseline_ratio REAL,
                scaling_param_efficiency REAL,
                scaling_gate_passed INTEGER,
                robustness_noise_score REAL,
                quant_int8_retention REAL,
                init_sensitivity_std REAL
            );

            CREATE TABLE program_results (
                result_id TEXT PRIMARY KEY,
                graph_json TEXT,
                routing_mode TEXT,
                graph_fingerprint TEXT,
                loss_ratio REAL,
                stage1_passed INTEGER,
                hellaswag_acc REAL,
                induction_screening_auc REAL,
                binding_screening_auc REAL,
                fp_jacobian_spectral_norm REAL,
                activation_sparsity_score REAL,
                validation_loss_ratio REAL,
                discovery_loss_ratio REAL,
                novelty_score REAL,
                trust_label TEXT,
                comparability_label TEXT,
                baseline_loss_ratio REAL,
                most_similar_to TEXT,
                param_count REAL,
                graph_n_params_estimate REAL,
                loss_improvement_rate REAL,
                throughput_tok_s REAL,
                forward_time_ms REAL,
                flops_forward REAL,
                flops_per_param REAL,
                sparsity_ratio REAL,
                peak_memory_mb REAL,
                routing_utilization_entropy REAL,
                routing_drop_rate REAL,
                routing_capacity_overflow_count REAL,
                routing_confidence_mean REAL,
                routing_confidence_std REAL,
                routing_tokens_total REAL,
                routing_tokens_processed REAL,
                routing_expert_count REAL,
                routing_expert_utilization_json TEXT,
                routing_savings_ratio REAL,
                depth_savings_ratio REAL,
                effective_depth_ratio REAL,
                recursion_savings_ratio REAL,
                init_sensitivity_std REAL,
                blimp_overall_accuracy REAL,
                ar_legacy_auc REAL
            );
            """
        )
        conn.executemany(
            """
            INSERT INTO leaderboard (
                entry_id, result_id, composite_score, tier,
                investigation_loss_ratio, screening_loss_ratio,
                validation_baseline_ratio, scaling_param_efficiency,
                scaling_gate_passed, robustness_noise_score,
                quant_int8_retention, init_sensitivity_std
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    "e1",
                    "r1",
                    10.0,
                    "screening",
                    None,
                    0.05,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                ),
                (
                    "e1b",
                    "r1b",
                    9.0,
                    "screening",
                    None,
                    0.06,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                ),
                (
                    "e2",
                    "r2",
                    8.0,
                    "screening",
                    None,
                    0.20,
                    0.80,
                    None,
                    None,
                    None,
                    None,
                    0.01,
                ),
            ],
        )
        conn.executemany(
            """
            INSERT INTO program_results (
                result_id, graph_json, routing_mode, graph_fingerprint, loss_ratio,
                stage1_passed, hellaswag_acc, induction_screening_auc, binding_screening_auc,
                fp_jacobian_spectral_norm, activation_sparsity_score,
                validation_loss_ratio, discovery_loss_ratio, novelty_score,
                trust_label, comparability_label, baseline_loss_ratio,
                most_similar_to, param_count, graph_n_params_estimate,
                loss_improvement_rate, throughput_tok_s, forward_time_ms,
                flops_forward, flops_per_param, sparsity_ratio, peak_memory_mb,
                routing_utilization_entropy, routing_drop_rate,
                routing_capacity_overflow_count, routing_confidence_mean,
                routing_confidence_std, routing_tokens_total,
                routing_tokens_processed, routing_expert_count,
                routing_expert_utilization_json, routing_savings_ratio,
                depth_savings_ratio, effective_depth_ratio,
                recursion_savings_ratio, init_sensitivity_std,
                blimp_overall_accuracy, ar_legacy_auc
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    "r1",
                    '{"nodes":[{"op_name":"attention"}]}',
                    None,
                    "fp-shared",
                    0.05,
                    1,
                    0.10,
                    None,
                    None,
                    None,
                    None,
                    0.05,
                    0.05,
                    0.10,
                    "candidate_grade",
                    None,
                    None,
                    None,
                    1.0e9,
                    None,
                    0.05,
                    500.0,
                    40.0,
                    1.0e12,
                    1000.0,
                    None,
                    800.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                ),
                (
                    "r1b",
                    '{"nodes":[{"op_name":"attention"}]}',
                    None,
                    "fp-shared",
                    0.06,
                    1,
                    0.09,
                    None,
                    None,
                    None,
                    None,
                    0.06,
                    0.06,
                    0.09,
                    "candidate_grade",
                    None,
                    None,
                    None,
                    1.0e9,
                    None,
                    0.04,
                    400.0,
                    45.0,
                    1.1e12,
                    1100.0,
                    None,
                    900.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                ),
                (
                    "r2",
                    '{"nodes":[{"op_name":"linear_proj"}]}',
                    None,
                    "fp-unique",
                    0.20,
                    1,
                    0.20,
                    None,
                    None,
                    None,
                    None,
                    0.20,
                    0.20,
                    0.90,
                    "backfill_observation",
                    None,
                    0.80,
                    "ref-x",
                    1.0e4,
                    None,
                    1.0,
                    30000.0,
                    2.0,
                    1.0e7,
                    10.0,
                    0.60,
                    50.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    0.50,
                    0.20,
                    0.50,
                    0.01,
                    0.80,
                    0.20,
                ),
            ],
        )
        conn.commit()
    finally:
        conn.close()


def test_select_candidates_dashboard_uses_backend_score_and_unique_limit(tmp_path):
    db_path = tmp_path / "rescreen.db"
    _init_schema(db_path)

    candidates = _select_candidates(
        db=db_path,
        tier=None,
        min_composite=None,
        max_composite=None,
        missing_probes=False,
        require_stage1=False,
        rank_by="dashboard",
        cohort=None,
        limit=2,
    )

    assert len(candidates) == 2
    assert [c["graph_fingerprint"] for c in candidates] == ["fp-unique", "fp-shared"]
    assert candidates[0]["dashboard_score"] == discovery_score(candidates[0])
    assert candidates[0]["dashboard_score"] > candidates[1]["dashboard_score"]
