"""Extended motifs: sparse, MoE, functional, exotic, missing ops.

Compound efficiency patterns, missing mixing/routing ops that need
motif coverage for grammar reachability.
"""

from __future__ import annotations

from typing import Tuple

from ._motif_types import (
    Motif,
    MotifStep,
    MOTIF_CLASS_ATTENTION,
    MOTIF_CLASS_CHANNEL,
    MOTIF_CLASS_CONV,
    MOTIF_CLASS_EFFICIENT_PROJ,
    MOTIF_CLASS_FFN,
    MOTIF_CLASS_GATE,
    MOTIF_CLASS_MATH_SPACE,
    MOTIF_CLASS_MOE,
    MOTIF_CLASS_SPARSE,
    MOTIF_CLASS_SSM,
)
from .op_roles import OpRole

EXTENDED_MOTIFS: Tuple[Motif, ...] = (
    # ── Sparse linear cores (2.0-2.2x lift) ────────────────────────
    Motif(
        name="sparse_nm",
        motif_class=MOTIF_CLASS_SPARSE,
        steps=(
            MotifStep("nm_sparse_linear", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="N:M sparse linear → activation (2.15x lift, LR 0.094)",
        support=36,
        avg_loss_ratio=0.094,
        lift=2.15,
    ),
    Motif(
        name="sparse_block",
        motif_class=MOTIF_CLASS_SPARSE,
        steps=(
            MotifStep("block_sparse_linear", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Block-sparse linear → activation (2.09x lift)",
        support=67,
        avg_loss_ratio=0.144,
        lift=2.09,
    ),
    Motif(
        name="sparse_ternary",
        motif_class=MOTIF_CLASS_SPARSE,
        steps=(
            MotifStep("ternary_projection", OpRole.PROJECT),
            MotifStep("silu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="1.58-bit ternary projection → activation (2.08x lift)",
        support=53,
        avg_loss_ratio=0.111,
        lift=2.08,
    ),
    Motif(
        name="sparse_semi_structured",
        motif_class=MOTIF_CLASS_SPARSE,
        steps=(
            MotifStep("semi_structured_2_4_linear", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="2:4 semi-structured sparse → activation (1.97x lift)",
        support=40,
        avg_loss_ratio=0.152,
        lift=1.97,
    ),
    # ── MoE cores (3.0-3.4x lift) ──────────────────────────────────
    Motif(
        name="moe_topk",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("moe_topk", OpRole.ROUTE),),
        description="Sparse top-k MoE (3.09x lift)",
        support=27,
        avg_loss_ratio=0.115,
        lift=3.09,
    ),
    Motif(
        name="moe_2expert",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("moe_2expert", OpRole.ROUTE),),
        description="Lightweight 2-expert MoE (2.59x lift)",
        support=63,
        avg_loss_ratio=0.114,
        lift=2.59,
    ),
    Motif(
        name="moe_proj_block",
        motif_class=MOTIF_CLASS_MOE,
        steps=(
            MotifStep("linear_proj", OpRole.PROJECT),
            MotifStep("moe_topk", OpRole.ROUTE),
            MotifStep("rmsnorm", OpRole.NORMALIZE),
        ),
        description="Proj → MoE → norm (sparse MoE block)",
        support=15,
        avg_loss_ratio=0.100,
        lift=2.5,
    ),
    # ── Functional / neural-field motifs ────────────────────────────
    Motif(
        name="mix_integral_kernel",
        motif_class=MOTIF_CLASS_SSM,
        steps=(
            MotifStep("integral_kernel", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Integral kernel mixing → projection",
        support=10,
        avg_loss_ratio=0.200,
        lift=2.5,
    ),
    Motif(
        name="mix_fixed_point",
        motif_class=MOTIF_CLASS_SSM,
        steps=(
            MotifStep("fixed_point_iter", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Fixed-point iteration → projection",
        support=5,
        avg_loss_ratio=0.250,
        lift=2.0,
    ),
    Motif(
        name="mix_basis_expansion",
        motif_class=MOTIF_CLASS_CONV,
        steps=(
            MotifStep("basis_expansion", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Basis expansion → activation (sinusoidal features)",
        support=8,
        avg_loss_ratio=0.200,
        lift=1.0,
    ),
    Motif(
        name="hyperbolic_residual_bridge",
        motif_class=MOTIF_CLASS_SSM,
        steps=(
            MotifStep("exp_map", OpRole.MIX),
            MotifStep("hyp_linear", OpRole.PROJECT),
            MotifStep("hyp_tangent_nonlinear", OpRole.ACTIVATE),
            MotifStep("log_map", OpRole.MIX),
        ),
        description="Leaderboard-seeded hyperbolic bridge block: exp_map → hyp_linear → tangent nonlinearity → log_map",
        support=2,
        avg_loss_ratio=0.010,
        lift=3.0,
    ),
    Motif(
        name="tropical_attention_gate",
        motif_class=MOTIF_CLASS_ATTENTION,
        steps=(
            MotifStep("rmsnorm", OpRole.NORMALIZE),
            MotifStep("tropical_attention", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Tropical block: rmsnorm bounds input → tropical attention → learnable proj",
        support=3,
        avg_loss_ratio=0.009,
        lift=2.1,
    ),
    Motif(
        name="clifford_attention_mix",
        motif_class=MOTIF_CLASS_CHANNEL,
        steps=(
            MotifStep("rmsnorm", OpRole.NORMALIZE),
            MotifStep("clifford_attention", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Clifford block: rmsnorm bounds input → clifford attention → learnable proj",
        support=3,
        avg_loss_ratio=0.008,
        lift=2.3,
    ),
    Motif(
        name="padic_hierarchy_block",
        motif_class=MOTIF_CLASS_SSM,
        steps=(
            MotifStep("rmsnorm", OpRole.NORMALIZE),
            MotifStep("padic_expand", OpRole.PROJECT),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="P-adic block: rmsnorm bounds input → padic expansion → learnable proj back",
        support=4,
        avg_loss_ratio=0.009,
        lift=2.4,
    ),
    # ── Compound Efficiency motifs ───────────────────────────────────
    Motif(
        name="sparse_moe_proj",
        motif_class=MOTIF_CLASS_MOE,
        steps=(
            MotifStep("nm_sparse_linear", OpRole.PROJECT),
            MotifStep("moe_topk", OpRole.ROUTE),
            MotifStep("rmsnorm", OpRole.NORMALIZE),
        ),
        description="Sparse linear → MoE routing → norm (compound efficiency)",
        support=10,
        avg_loss_ratio=0.095,
        lift=3.5,
    ),
    Motif(
        name="bottleneck_sparse",
        motif_class=MOTIF_CLASS_SPARSE,
        steps=(
            MotifStep("linear_proj_down", OpRole.PROJECT),
            MotifStep("nm_sparse_linear", OpRole.PROJECT),
            MotifStep("linear_proj_up", OpRole.PROJECT),
        ),
        description="Bottleneck D/4 → sparse linear → expand (compound savings)",
        support=8,
        avg_loss_ratio=0.110,
        lift=2.5,
    ),
    Motif(
        name="routed_ternary",
        motif_class=MOTIF_CLASS_SPARSE,
        steps=(
            MotifStep("ternary_projection", OpRole.PROJECT),
            MotifStep("silu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Ternary projection → activation (4x efficiency, routing via template)",
        support=5,
        avg_loss_ratio=0.088,
        lift=4.0,
    ),
    Motif(
        name="merge_scan",
        motif_class=MOTIF_CLASS_FFN,
        steps=(
            MotifStep("adjacent_token_merge", OpRole.MIX),
            MotifStep("swiglu_mlp", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Token merge → FFN → proj (sequence compression with safe successor)",
        support=6,
        avg_loss_ratio=0.105,
        lift=2.5,
    ),
    Motif(
        name="sparse_gated_ffn",
        motif_class=MOTIF_CLASS_FFN,
        steps=(
            MotifStep("block_sparse_linear", OpRole.PROJECT),
            MotifStep("swiglu_mlp", OpRole.GATE),
            MotifStep("linear_proj_down", OpRole.PROJECT),
        ),
        description="Block-sparse → SwiGLU → contract (sparse FFN)",
        support=12,
        avg_loss_ratio=0.098,
        lift=3.0,
    ),
    Motif(
        name="conditional_skip",
        motif_class=MOTIF_CLASS_GATE,
        steps=(MotifStep("gated_linear", OpRole.GATE),),
        description="Gated linear conditional compute (routing via template)",
        support=8,
        avg_loss_ratio=0.130,
        lift=2.0,
    ),
    # ── Missing mixing ops (catalog byte_safe, no motif) ─────────────
    Motif(
        name="attn_diff",
        motif_class=MOTIF_CLASS_ATTENTION,
        steps=(
            MotifStep("diff_attention", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Differential attention (dual softmax subtraction) → projection",
        support=0,
        avg_loss_ratio=0.0,
        lift=3.5,  # Boosted: 21.2% S1 rate in template analytics
    ),
    Motif(
        name="attn_gated_delta",
        motif_class=MOTIF_CLASS_ATTENTION,
        steps=(
            MotifStep("gated_delta", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Gated delta rule recurrence → projection",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.5,
    ),
    Motif(
        name="conv_only_block",
        motif_class=MOTIF_CLASS_CONV,
        steps=(
            MotifStep("conv_only", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="Pure conv stack (local + dilated) → projection",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.5,
    ),
    # ── Missing routing ops (catalog byte_safe, no motif) ────────────
    Motif(
        name="route_mod_topk",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("depth_token_mask", OpRole.ROUTE),),
        description="Mixture-of-Depths top-k token routing",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    Motif(
        name="route_speculative",
        motif_class=MOTIF_CLASS_GATE,
        steps=(MotifStep("cheap_verify_blend", OpRole.ROUTE),),
        description="Speculative dual-path blend (cheap + verify gate)",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="route_topk_gate",
        motif_class=MOTIF_CLASS_GATE,
        steps=(MotifStep("topk_gate", OpRole.GATE),),
        description="Sparse top-k gating over feature halves",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="route_lanes_block",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("gated_lane_blend", OpRole.ROUTE),),
        description="Multi-lane dispatch with learned lane scorer (template-only)",
        support=0,
        avg_loss_ratio=0.0,
        lift=0.0,
    ),
    Motif(
        name="route_recursion_block",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("depth_gated_transform", OpRole.ROUTE),),
        description="Adaptive recursion depth per token (template-only)",
        support=0,
        avg_loss_ratio=0.0,
        lift=0.0,
    ),
    Motif(
        name="route_topk_sparse",
        motif_class=MOTIF_CLASS_SPARSE,
        steps=(MotifStep("feature_sparsity", OpRole.ROUTE),),
        description="Hard top-k token selection with STE",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    # ── A. Efficient Projection motifs (unconditionally safe) ─────
    Motif(
        name="proj_bottleneck",
        motif_class=MOTIF_CLASS_EFFICIENT_PROJ,
        steps=(
            MotifStep("bottleneck_proj", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Bottleneck projection → activation",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    Motif(
        name="proj_low_rank",
        motif_class=MOTIF_CLASS_EFFICIENT_PROJ,
        steps=(
            MotifStep("low_rank_proj", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Low-rank projection → activation",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    Motif(
        name="proj_grouped",
        motif_class=MOTIF_CLASS_EFFICIENT_PROJ,
        steps=(
            MotifStep("grouped_linear", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Grouped linear → activation",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="proj_shared_basis",
        motif_class=MOTIF_CLASS_EFFICIENT_PROJ,
        steps=(
            MotifStep("shared_basis_proj", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Shared basis projection → activation",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="proj_tied",
        motif_class=MOTIF_CLASS_EFFICIENT_PROJ,
        steps=(
            MotifStep("tied_proj", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Tied projection → activation",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    # ── Recently-added ops: motifs for grammar reachability ─────
    Motif(
        name="codebook_proj",
        motif_class=MOTIF_CLASS_EFFICIENT_PROJ,
        steps=(
            MotifStep("embedding_lookup", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Soft codebook projection → activation (learnable VQ discretization)",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="kronecker_proj",
        motif_class=MOTIF_CLASS_EFFICIENT_PROJ,
        steps=(
            MotifStep("kronecker_linear", OpRole.PROJECT),
            MotifStep("gelu", OpRole.ACTIVATE, substitutable=True),
        ),
        description="Kronecker-factored projection → activation (128x param compression)",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="chebyshev_spectral",
        motif_class=MOTIF_CLASS_CHANNEL,
        steps=(
            MotifStep("chebyshev_spectral_mix", OpRole.MIX),
            MotifStep("rmsnorm", OpRole.NORMALIZE),
        ),
        description="Chebyshev spectral mix → normalize",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="n_way_routing",
        motif_class=MOTIF_CLASS_MOE,
        steps=(
            MotifStep("sparse_bottleneck_moe", OpRole.ROUTE),
            MotifStep("rmsnorm", OpRole.NORMALIZE),
        ),
        description="N-way sparse routing → normalize",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.5,
    ),
    # ── True routing — heterogeneous expert dispatch ─────────────────
    Motif(
        name="true_hetero_moe",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("hetero_moe", OpRole.ROUTE),),
        description="True heterogeneous MoE: routes tokens to attention, conv, or SSM experts",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.5,
    ),
    Motif(
        name="true_arch_router",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("arch_router", OpRole.ROUTE),),
        description="Architecture router: tokens choose transformer, mamba, or MLP style",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.5,
    ),
    Motif(
        name="true_compute_budget",
        motif_class=MOTIF_CLASS_MOE,
        steps=(MotifStep("compute_budget_router", OpRole.ROUTE),),
        description="Compute budget router: easy→cheap linear, medium→conv, hard→attention",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.5,
    ),
    Motif(
        name="spectral_filter_block",
        motif_class=MOTIF_CLASS_CHANNEL,
        steps=(
            MotifStep("spectral_filter", OpRole.MIX),
            MotifStep("rmsnorm", OpRole.NORMALIZE),
        ),
        description="spectral_filter → rmsnorm (satisfies must_precede constraint)",
        support=0,
        avg_loss_ratio=0.0,
        lift=1.0,
    ),
    Motif(
        name="tropical_matmul_block",
        motif_class=MOTIF_CLASS_MATH_SPACE,
        steps=(
            MotifStep("tropical_matmul", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="tropical_matmul → linear_proj (back to euclidean)",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    # ── Tropical ops (real→real, no space conflict) ─────────────────
    Motif(
        name="tropical_gate_block",
        motif_class=MOTIF_CLASS_MATH_SPACE,
        steps=(
            MotifStep("tropical_gate", OpRole.GATE),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="tropical_gate → linear_proj (shortest-path gating)",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    Motif(
        name="tropical_center_norm",
        motif_class=MOTIF_CLASS_MATH_SPACE,
        steps=(
            MotifStep("tropical_center", OpRole.NORMALIZE),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="tropical_center → linear_proj (subtract tropical baseline)",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    # ── Grade mix (must follow clifford op per MATH_SPACE_RULES) ──
    Motif(
        name="clifford_attention_grade",
        motif_class=MOTIF_CLASS_MATH_SPACE,
        steps=(
            MotifStep("rmsnorm", OpRole.NORMALIZE),
            MotifStep("clifford_attention", OpRole.MIX),
            MotifStep("grade_mix", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="rmsnorm → clifford_attention → grade_mix → proj (full Clifford block)",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    # ── Padic residual bridge (padic→real output) ─────────────────
    Motif(
        name="padic_residual_bridge",
        motif_class=MOTIF_CLASS_MATH_SPACE,
        steps=(
            MotifStep("rmsnorm", OpRole.NORMALIZE),
            MotifStep("padic_expand", OpRole.PROJECT),
            MotifStep("padic_residual", OpRole.RESIDUAL),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="rmsnorm → padic_expand → padic_residual → proj (multi-res p-adic bridge)",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    # ── Space-bridging motifs (euclidean → non-euclidean → euclidean) ──
    Motif(
        name="poincare_add_bridge",
        motif_class=MOTIF_CLASS_MATH_SPACE,
        steps=(
            MotifStep("exp_map", OpRole.MIX),
            MotifStep("poincare_add", OpRole.RESIDUAL),
            MotifStep("log_map", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="exp_map → poincare_add → log_map → proj (Mobius addition bridge)",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
    # hyp_distance: binary op, handled by tpl_hyp_distance_scoring template
    Motif(
        name="ultrametric_attention_bridge",
        motif_class=MOTIF_CLASS_MATH_SPACE,
        steps=(
            MotifStep("rmsnorm", OpRole.NORMALIZE),
            MotifStep("padic_expand", OpRole.PROJECT),
            MotifStep("ultrametric_attention", OpRole.MIX),
            MotifStep("linear_proj", OpRole.PROJECT),
        ),
        description="rmsnorm → padic_expand → ultrametric_attention → proj (p-adic attention bridge)",
        support=0,
        avg_loss_ratio=0.0,
        lift=2.0,
    ),
)
