"""Routing-capable template manifest for graph-generation hot paths."""

from __future__ import annotations

from typing import FrozenSet


ROUTING_CAPABLE_TEMPLATE_NAMES: FrozenSet[str] = frozenset(
    {
        "adaptive_conv_ffn",
        "adaptive_lane_recursion",
        "adaptive_sparse",
        "adaptive_ssm_chain",
        "arch_router_block",
        "attn_routing_block",
        "attn_sparse_moe",
        "attn_spiking_hybrid",
        "attn_three_way_split",
        "cascaded_early_exit",
        "cawn_mixer_block",
        "codex_ssm_mla_gated_block",
        "compute_budget_block",
        "conditional_compute",
        "depth_gated_block",
        "depth_gated_block_matmul_norm",
        "depth_gated_block_matmul_stable",
        "depth_token_mask_block",
        "diff_attn_moe",
        "diff_attn_routing",
        "difficulty_routed_block",
        "dual_routing_deep",
        "dual_routing_stack",
        "feature_sparse_block",
        "gated_lane_blend_block",
        "graph_attn_moe",
        "hetero_moe_block",
        "hybrid_sparse_triplet_router",
        "intelligent_multilane_router",
        "latent_attn_conv_hybrid",
        "latent_attn_ffn_block",
        "latent_attn_moe",
        "latent_attn_padic_hybrid",
        "latent_attn_sparse_ffn",
        "latent_attn_ssm_hybrid",
        "latent_compress_block",
        "latent_compress_rwkv",
        "local_attn_routing",
        "mixed_recursion",
        "moe",
        "multiscale_difficulty_router",
        "multiscale_difficulty_router_adaptive_attn_ssm",
        "multiscale_rich_lane_router",
        "n_way_moe_block",
        "pq_embedding_moe_block",
        "recursive_attn_ssm_depth",
        "recursive_attn_ssm_hybrid",
        "recursive_depth_router",
        "recursive_moe_attn",
        "routed_bottleneck",
        "routing_conditioned_moe",
        "signal_routed_compression",
        "sparse_moe_block",
        "sparse_relation_graph_block",
        "spiking_moe_block",
        "spiking_residual_block",
        "spiking_stdp_block",
        "three_lane_adaptive",
        "three_way_split",
        "token_merge_block",
        "token_merge_conv",
        "token_program_interpreter_block",
        "tropical_center_block",
        "typed_slot_memory_block",
        "ultrametric_attention_block",
    }
)
