"""Structured attention template manifest.

This is the native-ready registration surface for attention-family templates.
`templates.py` consumes these tables directly instead of repeating attention
template names across import lists, registry entries, and default-weight maps.
"""

from __future__ import annotations

from ._templates_attention import (
    tpl_attn_bottleneck_hybrid,
    tpl_attn_chebyshev_hybrid,
    tpl_attn_conditional_compute,
    tpl_attn_conv_hybrid,
    tpl_attn_cross_dim,
    tpl_attn_exp_gated,
    tpl_attn_gated_product,
    tpl_attn_gated_residual,
    tpl_attn_multi_head_mix,
    tpl_attn_residual_block,
    tpl_attn_routing_block,
    tpl_attn_rwkv_hybrid,
    tpl_attn_sparse_moe,
    tpl_attn_ssm_hybrid,
    tpl_attn_state_space_hybrid,
    tpl_attn_three_way_split,
    tpl_cascaded_attn_ffn,
    tpl_diff_attn_gated_ffn,
    tpl_diff_attn_routing,
    tpl_dual_attn_block,
    tpl_local_attn_ffn_block,
    tpl_local_attn_routing,
    tpl_local_attn_swiglu,
)
from ._templates_attention_tail import (
    GENERATED_ATTN_DEFAULT_WEIGHTS,
    GENERATED_ATTN_REGISTRY_TEMPLATES,
    tpl_associative_memory_block,
    tpl_dplr_gated_delta_block,
    tpl_entmax_attention_block,
    tpl_learnable_semiring_attention_block,
    tpl_attn_decay_sequence,
    tpl_attn_gated_maximum,
    tpl_attn_hyperbolic,
    tpl_attn_linear_no_matmul_ffn,
    tpl_attn_linear_no_matmul_ffn_dense_tail,
    tpl_attn_linear_no_matmul_ffn_direct_recovery,
    tpl_attn_linear_softmax_recovery_control,
    tpl_attn_normalized_matmul,
    tpl_attn_normalized_matmul_pinned,
    tpl_attn_safe_division,
    tpl_attn_softmax_matmul_sparse_tail,
    tpl_attn_softmax_normalized_matmul,
    tpl_attn_softmax_normalized_matmul_compact_ffn,
    tpl_attn_softmax_normalized_matmul_fixed_tail_norm,
    tpl_attn_softmax_normalized_matmul_v2,
    tpl_attn_spiking_hybrid,
    tpl_attn_spectral_filter,
    tpl_codex_ssm_delta_memory_block,
    tpl_codex_ssm_local_recall_block,
    tpl_codex_ssm_mla_gated_block,
    tpl_codex_ssm_retention_block,
    tpl_diff_attn_conv_hybrid,
    tpl_difficulty_routed_attention_block,
    tpl_gated_progressive_attention_block,
    tpl_graph_attn_sparse_ffn,
    tpl_graph_attn_ssm_recursive,
    tpl_latent_attn_conv_hybrid,
    tpl_latent_attn_padic_hybrid,
    tpl_latent_attn_ssm_hybrid,
    tpl_linear_attn_ffn_block,
    tpl_linear_attn_sparse_ffn,
    tpl_local_attn_moe,
    tpl_local_attn_ssm_hybrid,
    tpl_long_conv_hyena_block,
    tpl_mixture_of_recursions_block,
    tpl_phase_lock_attention_block,
    tpl_product_key_memory_block,
    tpl_reciprocal_rank_attention_block,
    tpl_reciprocal_semiring_attention_block,
    tpl_retention_mix_block,
    tpl_recursive_attn_ssm_depth,
    tpl_sparsemax_attention_block,
    tpl_stdp_reciprocal_memory_block,
    tpl_strided_attention_block,
    tpl_token_hodge_mixer_block,
    tpl_wavelet_packet_mix_block,
)

ATTENTION_TEMPLATE_REGISTRY = {
    "attn_residual_block": tpl_attn_residual_block,
    "attn_gated_residual": tpl_attn_gated_residual,
    "attn_three_way_split": tpl_attn_three_way_split,
    "attn_conditional_compute": tpl_attn_conditional_compute,
    "attn_cross_dim": tpl_attn_cross_dim,
    "attn_multi_head_mix": tpl_attn_multi_head_mix,
    "local_attn_ffn_block": tpl_local_attn_ffn_block,
    "local_attn_swiglu": tpl_local_attn_swiglu,
    "diff_attn_gated_ffn": tpl_diff_attn_gated_ffn,
    "attn_ssm_hybrid": tpl_attn_ssm_hybrid,
    "attn_conv_hybrid": tpl_attn_conv_hybrid,
    "attn_rwkv_hybrid": tpl_attn_rwkv_hybrid,
    "attn_bottleneck_hybrid": tpl_attn_bottleneck_hybrid,
    "attn_routing_block": tpl_attn_routing_block,
    "dual_attn_block": tpl_dual_attn_block,
    "attn_state_space_hybrid": tpl_attn_state_space_hybrid,
    "cascaded_attn_ffn": tpl_cascaded_attn_ffn,
    "attn_exp_gated": tpl_attn_exp_gated,
    "attn_decay_sequence": tpl_attn_decay_sequence,
    "attn_gated_product": tpl_attn_gated_product,
    "diff_attn_routing": tpl_diff_attn_routing,
    "local_attn_routing": tpl_local_attn_routing,
    "attn_chebyshev_hybrid": tpl_attn_chebyshev_hybrid,
    "attn_sparse_moe": tpl_attn_sparse_moe,
    "attn_gated_maximum": tpl_attn_gated_maximum,
    "attn_hyperbolic": tpl_attn_hyperbolic,
    "attn_spectral_filter": tpl_attn_spectral_filter,
    "attn_normalized_matmul": tpl_attn_normalized_matmul,
    "attn_softmax_normalized_matmul": tpl_attn_softmax_normalized_matmul,
    "attn_softmax_normalized_matmul_compact_ffn": tpl_attn_softmax_normalized_matmul_compact_ffn,
    "attn_softmax_normalized_matmul_fixed_tail_norm": tpl_attn_softmax_normalized_matmul_fixed_tail_norm,
    "attn_softmax_normalized_matmul_v2": tpl_attn_softmax_normalized_matmul_v2,
    "attn_linear_softmax_recovery_control": tpl_attn_linear_softmax_recovery_control,
    "attn_linear_no_matmul_ffn": tpl_attn_linear_no_matmul_ffn,
    "attn_linear_no_matmul_ffn_dense_tail": tpl_attn_linear_no_matmul_ffn_dense_tail,
    "attn_linear_no_matmul_ffn_direct_recovery": tpl_attn_linear_no_matmul_ffn_direct_recovery,
    "attn_softmax_matmul_sparse_tail": tpl_attn_softmax_matmul_sparse_tail,
    "latent_attn_conv_hybrid": tpl_latent_attn_conv_hybrid,
    "diff_attn_conv_hybrid": tpl_diff_attn_conv_hybrid,
    "attn_safe_division": tpl_attn_safe_division,
    "latent_attn_ssm_hybrid": tpl_latent_attn_ssm_hybrid,
    "local_attn_ssm_hybrid": tpl_local_attn_ssm_hybrid,
    "attn_spiking_hybrid": tpl_attn_spiking_hybrid,
    "local_attn_moe": tpl_local_attn_moe,
    "linear_attn_ffn_block": tpl_linear_attn_ffn_block,
    "linear_attn_sparse_ffn": tpl_linear_attn_sparse_ffn,
    "graph_attn_sparse_ffn": tpl_graph_attn_sparse_ffn,
    "attn_normalized_matmul_pinned": tpl_attn_normalized_matmul_pinned,
    "difficulty_routed_attention_block": tpl_difficulty_routed_attention_block,
    "strided_attention_block": tpl_strided_attention_block,
    "gated_progressive_attention_block": tpl_gated_progressive_attention_block,
    "long_conv_hyena_block": tpl_long_conv_hyena_block,
    "associative_memory_block": tpl_associative_memory_block,
    "mixture_of_recursions_block": tpl_mixture_of_recursions_block,
    "sparsemax_attention_block": tpl_sparsemax_attention_block,
    "entmax_attention_block": tpl_entmax_attention_block,
    "learnable_semiring_attention_block": tpl_learnable_semiring_attention_block,
    "reciprocal_rank_attention_block": tpl_reciprocal_rank_attention_block,
    "reciprocal_semiring_attention_block": tpl_reciprocal_semiring_attention_block,
    "phase_lock_attention_block": tpl_phase_lock_attention_block,
    "stdp_reciprocal_memory_block": tpl_stdp_reciprocal_memory_block,
    "dplr_gated_delta_block": tpl_dplr_gated_delta_block,
    "token_hodge_mixer_block": tpl_token_hodge_mixer_block,
    "wavelet_packet_mix_block": tpl_wavelet_packet_mix_block,
    "retention_mix_block": tpl_retention_mix_block,
    "product_key_memory_block": tpl_product_key_memory_block,
    "codex_ssm_retention_block": tpl_codex_ssm_retention_block,
    "codex_ssm_delta_memory_block": tpl_codex_ssm_delta_memory_block,
    "codex_ssm_mla_gated_block": tpl_codex_ssm_mla_gated_block,
    "codex_ssm_local_recall_block": tpl_codex_ssm_local_recall_block,
    "recursive_attn_ssm_depth": tpl_recursive_attn_ssm_depth,
    "latent_attn_padic_hybrid": tpl_latent_attn_padic_hybrid,
    "graph_attn_ssm_recursive": tpl_graph_attn_ssm_recursive,
    **GENERATED_ATTN_REGISTRY_TEMPLATES,
}


ATTENTION_TEMPLATE_DEFAULT_WEIGHTS = {
    "attn_residual_block": 3.5,
    "attn_gated_residual": 3.5,
    "attn_three_way_split": 4.0,
    "attn_conditional_compute": 3.5,
    "attn_cross_dim": 3.0,
    "attn_multi_head_mix": 3.5,
    "local_attn_ffn_block": 4.0,
    "local_attn_swiglu": 4.0,
    "diff_attn_gated_ffn": 3.5,
    "attn_ssm_hybrid": 3.5,
    "attn_conv_hybrid": 3.5,
    "attn_rwkv_hybrid": 3.5,
    "attn_bottleneck_hybrid": 4.0,
    "attn_routing_block": 3.0,
    "dual_attn_block": 3.0,
    "attn_state_space_hybrid": 3.5,
    "cascaded_attn_ffn": 3.0,
    "attn_exp_gated": 3.0,
    "attn_decay_sequence": 3.0,
    "attn_gated_product": 3.0,
    "diff_attn_routing": 3.5,
    "local_attn_routing": 0.5,
    "attn_chebyshev_hybrid": 3.0,
    "attn_sparse_moe": 3.5,
    "attn_gated_maximum": 3.0,
    "attn_hyperbolic": 3.0,
    "attn_spectral_filter": 3.5,
    "attn_normalized_matmul": 4.0,
    "attn_softmax_normalized_matmul": 5.25,
    "attn_softmax_normalized_matmul_compact_ffn": 3.0,
    "attn_softmax_normalized_matmul_fixed_tail_norm": 2.0,
    "attn_softmax_normalized_matmul_v2": 4.0,
    "attn_linear_softmax_recovery_control": 4.0,
    "attn_linear_no_matmul_ffn": 3.5,
    "attn_linear_no_matmul_ffn_dense_tail": 2.0,
    "attn_linear_no_matmul_ffn_direct_recovery": 2.0,
    "attn_softmax_matmul_sparse_tail": 4.0,
    "latent_attn_conv_hybrid": 6.0,
    "diff_attn_conv_hybrid": 3.5,
    "attn_safe_division": 3.0,
    "latent_attn_ssm_hybrid": 4.0,
    "local_attn_ssm_hybrid": 5.25,
    "attn_spiking_hybrid": 3.0,
    "local_attn_moe": 0.5,
    "linear_attn_ffn_block": 2.5,
    "linear_attn_sparse_ffn": 3.75,
    "graph_attn_sparse_ffn": 3.0,
    "attn_normalized_matmul_pinned": 6.0,
    "difficulty_routed_attention_block": 5.0,
    "strided_attention_block": 5.0,
    "gated_progressive_attention_block": 5.0,
    "long_conv_hyena_block": 4.5,
    "associative_memory_block": 4.5,
    "mixture_of_recursions_block": 5.0,
    "sparsemax_attention_block": 4.5,
    "entmax_attention_block": 4.5,
    "learnable_semiring_attention_block": 4.5,
    "reciprocal_rank_attention_block": 4.5,
    "reciprocal_semiring_attention_block": 4.5,
    "phase_lock_attention_block": 4.5,
    "stdp_reciprocal_memory_block": 4.75,
    "dplr_gated_delta_block": 4.5,
    "token_hodge_mixer_block": 4.0,
    "wavelet_packet_mix_block": 4.0,
    "retention_mix_block": 4.5,
    "product_key_memory_block": 4.5,
    "codex_ssm_retention_block": 4.5,
    "codex_ssm_delta_memory_block": 4.5,
    "codex_ssm_mla_gated_block": 4.5,
    "codex_ssm_local_recall_block": 4.0,
    "recursive_attn_ssm_depth": 5.5,
    "latent_attn_padic_hybrid": 5.0,
    "graph_attn_ssm_recursive": 4.5,
    **GENERATED_ATTN_DEFAULT_WEIGHTS,
}
