"""Structured research/reference template manifest.

This is the registration surface for research-family templates.
`templates.py` consumes these tables directly instead of repeating research
template names across import lists, registry entries, and default-weight maps.
"""

from __future__ import annotations

from ._templates_research import (
    tpl_arch_router_block,
    tpl_compute_budget_block,
    tpl_cross_dim_mixer,
    tpl_cumulative_sequence,
    tpl_diff_attention_block,
    tpl_dual_axis_block,
    tpl_exp_gated_residual,
    tpl_fused_gelu_ffn,
    tpl_gpt2_reference,
    tpl_graph_attention_block,
    tpl_hetero_moe_block,
    tpl_integral_kernel_block,
    tpl_kronecker_block,
    tpl_local_attention_block,
    tpl_log_gated,
    tpl_mamba_reference,
    tpl_multi_head_mix_block,
    tpl_reduce_attend,
    tpl_reciprocal_gated,
    tpl_rope_attention_block,
    tpl_rwkv_block,
    tpl_rwkv_double_norm,
    tpl_rwkv_sparse_chain,
    tpl_sign_ste_gated,
    tpl_spiking_stdp_block,
    tpl_sqrt_gated_ffn,
    tpl_state_space_block,
    tpl_ultrametric_attention_block,
    tpl_windowed_attention,
    tpl_chebyshev_block,
)


RESEARCH_TEMPLATE_REGISTRY = {
    "cumulative_sequence": tpl_cumulative_sequence,
    "sqrt_gated_ffn": tpl_sqrt_gated_ffn,
    "reduce_attend": tpl_reduce_attend,
    "fused_gelu_ffn": tpl_fused_gelu_ffn,
    "exp_gated_residual": tpl_exp_gated_residual,
    "integral_kernel_block": tpl_integral_kernel_block,
    "windowed_attention": tpl_windowed_attention,
    "local_attention_block": tpl_local_attention_block,
    "state_space_block": tpl_state_space_block,
    "rwkv_block": tpl_rwkv_block,
    "rwkv_double_norm": tpl_rwkv_double_norm,
    "rwkv_sparse_chain": tpl_rwkv_sparse_chain,
    "reciprocal_gated": tpl_reciprocal_gated,
    "sign_ste_gated": tpl_sign_ste_gated,
    "log_gated": tpl_log_gated,
    "ultrametric_attention_block": tpl_ultrametric_attention_block,
    "diff_attention_block": tpl_diff_attention_block,
    "graph_attention_block": tpl_graph_attention_block,
    "multi_head_mix_block": tpl_multi_head_mix_block,
    "chebyshev_block": tpl_chebyshev_block,
    "kronecker_block": tpl_kronecker_block,
    "spiking_stdp_block": tpl_spiking_stdp_block,
    "rope_attention_block": tpl_rope_attention_block,
    "gpt2_reference": tpl_gpt2_reference,
    "mamba_reference": tpl_mamba_reference,
    "hetero_moe_block": tpl_hetero_moe_block,
    "arch_router_block": tpl_arch_router_block,
    "compute_budget_block": tpl_compute_budget_block,
    "cross_dim_mixer": tpl_cross_dim_mixer,
    "dual_axis_block": tpl_dual_axis_block,
}


RESEARCH_TEMPLATE_DEFAULT_WEIGHTS = {
    "cumulative_sequence": 2.5,
    "sqrt_gated_ffn": 2.5,
    "reduce_attend": 3.0,
    "fused_gelu_ffn": 3.0,
    "exp_gated_residual": 2.5,
    "integral_kernel_block": 3.0,
    "windowed_attention": 3.0,
    "local_attention_block": 3.0,
    "state_space_block": 3.5,
    "rwkv_block": 1.0,
    "rwkv_double_norm": 5.0,
    "rwkv_sparse_chain": 4.0,
    "reciprocal_gated": 2.5,
    "sign_ste_gated": 2.5,
    "log_gated": 2.5,
    "ultrametric_attention_block": 3.5,
    "diff_attention_block": 3.5,
    "graph_attention_block": 3.5,
    "multi_head_mix_block": 4.0,
    "chebyshev_block": 3.0,
    "kronecker_block": 3.0,
    "spiking_stdp_block": 3.0,
    "rope_attention_block": 1.0,  # Demoted: 4.9% S1 rate
    "gpt2_reference": 3.0,
    "mamba_reference": 3.0,
    "hetero_moe_block": 4.0,
    "arch_router_block": 4.0,
    "compute_budget_block": 4.0,
    "cross_dim_mixer": 3.5,
    "dual_axis_block": 3.0,
}
