"""Code generation — turn ProposalSpecs into runnable nn.Module primitives."""

from .code_generator import generate_module, generate_module_from_spec
from .memory_primitives import (
    CausalFastWeightMemoryLane,
    CausalSlotRouterMemoryLane,
    HierarchicalResidualCompressorLane,
    PadicSurpriseMemoryLane,
    TropicalSurpriseMemoryLane,
)
from .primitive_templates import (
    CalculusAugmentedLane,
    CliffordAttention,
    FiniteDifferenceCalculusLane,
    FourierBasisLane,
    GraphDiffusionAdapterLane,
    GraphDiffusionLane,
    LowRankAdapterLane,
    LowRankFactorizedLane,
    MultiscaleWaveletAdapterLane,
    MultiscaleWaveletLane,
    PadicProjection,
    RandomFeatureKernelAdapterLane,
    RandomFeatureKernelLane,
    SparseBandedAdapterLane,
    SparseBandedMatrixLane,
    SpikingActivationGate,
    SymplecticResidualMixerLane,
    TopKLinear,
    TropicalAttention,
    TropicalStateSpace,
    TropicalTopKStateSpace,
)

__all__ = [
    "CalculusAugmentedLane",
    "CausalFastWeightMemoryLane",
    "CausalSlotRouterMemoryLane",
    "CliffordAttention",
    "FiniteDifferenceCalculusLane",
    "FourierBasisLane",
    "GraphDiffusionAdapterLane",
    "GraphDiffusionLane",
    "HierarchicalResidualCompressorLane",
    "LowRankAdapterLane",
    "LowRankFactorizedLane",
    "MultiscaleWaveletAdapterLane",
    "MultiscaleWaveletLane",
    "PadicProjection",
    "PadicSurpriseMemoryLane",
    "RandomFeatureKernelAdapterLane",
    "RandomFeatureKernelLane",
    "SparseBandedAdapterLane",
    "SparseBandedMatrixLane",
    "SpikingActivationGate",
    "SymplecticResidualMixerLane",
    "TopKLinear",
    "TropicalAttention",
    "TropicalStateSpace",
    "TropicalSurpriseMemoryLane",
    "TropicalTopKStateSpace",
    "generate_module",
    "generate_module_from_spec",
]
